image_detector:
  ros__parameters:
    camera:
      input_topic: "/camera/resize_hsv/image_raw"

    detection:
      line:
        rho: 1.0
        theta: 1.0
<<<<<<< HEAD
        threshold: 60
        min_line_length: 100.0
        max_line_gap: 50.0
=======
        threshold: 50
        min_line_length: 100.0
        max_line_gap: 20.0
>>>>>>> cbd98050ea604e3a746849be1f679eeff0887e1f
        adaptive_block_size: 15
        adaptive_C: 5.0
        morph_kernel_size: 5

    # ballsをdetectionの外に移動し、フラットな構造にする
    detection.balls.0.name: "red"
    detection.balls.0.hsv_lower: [0, 10, 80]
    detection.balls.0.hsv_upper: [10, 250, 255]
    
    detection.balls.1.name: "blue"
    detection.balls.1.hsv_lower: [100, 100, 0]
    detection.balls.1.hsv_upper: [120, 255, 255]
    
    detection.balls.2.name: "yellow"
    detection.balls.2.hsv_lower: [15, 100, 100]
    detection.balls.2.hsv_upper: [40, 255, 255]

    outputs:
      line_topic: "/detection/lines"
      ball_topic: "/detection/balls"

    node_parameters:
      queue_size: 10