image_detector:
  ros__parameters:
    camera:
      input_topic: "/camera/resize_hsv/image_raw"

    detection:
      line:
        rho: 1.0
        theta: 1.0
        threshold: 50
        min_line_length: 50.0
        max_line_gap: 10.0

    # ballsをdetectionの外に移動し、フラットな構造にする
    detection.balls.0.name: "red"
    detection.balls.0.hsv_lower: [40, 10, 140]
    detection.balls.0.hsv_upper: [90, 140, 255]
    
    detection.balls.1.name: "blue"
    detection.balls.1.hsv_lower: [40, 140, 0]
    detection.balls.1.hsv_upper: [70, 255, 255]
    
    detection.balls.2.name: "yellow"
    detection.balls.2.hsv_lower: [20, 150, 100]
    detection.balls.2.hsv_upper: [50, 255, 255]

    outputs:
      line_topic: "/detection/lines"
      ball_topic: "/detection/balls"

    node_parameters:
      queue_size: 10